name: mainpassingvalues

on: push

jobs:
  call_reusable:
    uses: ./.github/workflows/readpassingvalue.yaml
    with:
      name: "Eswar Reddy Vatticharla vatticharla"
      project: "Roboshop"
      # component: "Dev"
      # environment: "DevEnv"