name: readpassingvalue

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Name
        run: echo "${{ inputs.name }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check files
        run: ls -la

      - name: Install npm dependencies
        run: npm install

      - name: Checking the unit testing
        run: echo "Unit testing is successful"