name: Reusable Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Name
        run: echo "Hello ${{ inputs.name }}"

      - name: Print Name
        run: |
          echo "Hello ${{ inputs.name }}"

      - name: Print Project
        run: |
          echo "Project: ${{ inputs.project }}"

      - name: Print Component
        run: |
          echo "Component: ${{ inputs.component }}"

      - name: Print Environment
        run: |
          echo "Environment: ${{ inputs.environment }}"