name: Reusable Workflow 2

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      Project:
        required: true
        type: string
      componet:
        required: true
        type: string
      Environemnt:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello vatticharla ${{ inputs.name }}"

      - run: echo "${{ inputs.Project }}"

      - run: echo "${{ inputs.componet }}"

      - run: echo "${{ inputs.Environemnt }}"