name: readpassingvalue

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Name
        run: echo "${{ inputs.name }}"

      - name : install npm dependincies
        run: npm install

      - name: cheking the unit testing
        run: "echo {{unit testing is sucessfull}}"
       